dist: xenial

language: java

jdk:
  - openjdk11

install:
  - mvn install -DskipTests=true -B -V
  - mvn test -B

deploy:
  provider: heroku
  api_key: ${herokuappkey}
  app: kk-cat-mash