dist: xenial

language: java

jdk:
  - openjdk11

services:
  - docker

before_install:
  - docker pull adoptopenjdk/openjdk11:ubi

install: skip

script:
  - mvn package

after_success:
  - if [ ! -z "$TRAVIS_TAG" ]; then
      docker login -u $DOCKER_USER -p $DOCKER_PASS;
      docker-compose build;
      docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TRAVIS_TAG;
      docker push $IMAGE_NAME:$TRAVIS_TAG;
    fi

deploy:
  provider: heroku
  api_key: ${herokuappkey}
  app: kk-cat-mash
  on:
    tags: true